### ISSUE TITLE
Error after updating to latest version with Homebridge Config UI

### ISSUE THREAD

**Issue by JoshuaHolme** [nzapponi/homebridge-simplisafe3#113]
I tried to update to the latest version of this plugin using the HomeBridge Config UI, but got the following error.

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! core-js@3.6.5 postinstall: `node -e "try{require('./postinstall')}catch
(e){}"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the core-js@3.6.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Windows\system32\config\systemprofile\AppData\Roaming\npm-cache\
_logs\2020-05-17T19_57_40_171Z-debug.log
```

**Comment by JoshuaHolme** [comment]
I was able to update it through the command prompt with `npm install -g --unsafe-perm homebridge-simplisafe3` but I figured I would log the issue also

**Comment by nikonratm** [comment]
Joshua, if you install the plugin using the `--unsafe-perm` flag you will not be able to update it via Config UI X because it is installed under a different user ([thats what that flag does](https://geedew.com/What-does-unsafe-perm-in-npm-actually-do/)). I recommend you uninstall `sudo npm remove -g homebridge-simplisafe3` and then re-install via Config UI X. Be sure to take a backup first but if you just uninstall and re-install the plugin you shouldn't lose anything (but again, backup just in case).
