### ISSUE TITLE
Doorbell Notification for tvOS 14

### ISSUE THREAD

**Issue by brianhollings** [nzapponi/homebridge-simplisafe3#137]
**Is your feature request related to a problem? Please describe:**
In tvOS 14, there is the ability for doorbell notification when the doorbell is rang.
**Describe the solution you'd like:**
When door bell is rang the Apple TV displays the doorbell notification.

**Comment by shamoon** [comment]
Hi @brianhollings This plugin, and homebridge in general, doesn’t really have any control over this. If you are referring to the facial recognition notifications shown off at WWDC they require HKSV which is not supported by homebridge and may never be due to its requirements. Beyond that, any notifications from the doorbell will be handled by tvOS as Apple has built it. tvOS 14 is still in beta, of course, so it remains to be seen where they end up on these notifications but I do not expect this plugin or homebridge to need any updates to for that
