### ISSUE TITLE
"SSAPI socket error: Not authorized"

### ISSUE THREAD

**Issue by madrobby** [nzapponi/homebridge-simplisafe3#143]
**Describe The Bug:**
I keep seeing `[8/24/2020, 9:11:34 PM] [Home Alarm] SSAPI socket error: Not authorized` error messages in my log. There's one red log line per second.

I have to restart Homebridge completely for the connection to SimpliSafe to work again.

Please note: I'm running two instances of Homebridge on this machine because I have two alarm systems. Could it be that the two instances together cause API quota limits per IP address? Is there a way to limit API call frequency?

**To Reproduce:**
Unknown.

**Expected behavior:**
No errors. Perhaps if this error occurs, try to reconnect to SimpliSafe.

**Logs:**
I will run with debug mode and add to this ticket.

```
Paste Homebridge Logs here
```

**Homebridge Config:**
```
{
            "name": "Home Alarm",
            "auth": {
                "username": "XXXXXXXXXXX",
                "password": "XXXXXXXXXXX"
            },
            "cameras": true,
            "debug": true,
            "subscriptionId": "XXXXXXXXX",
            "sensorRefresh": 15,
            "persistAccessories": false,
            "resetSimpliSafeId": false,
            "cameraOptions": {
                "enableHwaccelRpi": false,
                "ffmpegPath": "/usr/local/bin/ffmpeg"
            },
            "platform": "homebridge-simplisafe3.SimpliSafe 3"
        },
```

**Environment:**

* **Plugin version**: homebridge-simplisafe3@1.6.7 
* **Node.js Version**: v12.18.1
* **NPM Version**: 6.14.7
* **Homebridge Version**: 1.1.2
* **Operating System**: macOS 10.15.6

**Comment by shamoon** [comment]
Yes @madrobby, this issue is definitely related to the fact that you are running two instances. Which is unfortunate because otherwise it does seem like a good solution to your problem #142. One thing that might help would be to change the `sensorRefresh` time for each of them to a bit longer. We dont know exactly what the right number is but SS servers seem to temporarily throttle/ban users based on their IP, so effectively you are hitting their servers twice the usual amount.

Which leads me to the next thing which is that I took a look at your request #142. Again, unfortunately I think it represents a pretty significant refactoring of the code for a pretty limited use (you are the only person so far to request the feature) but perhaps more importantly it would still suffer from the same issue to what you are seeing here. SimpliSafe doesnt let you poll two (or more) alarms at once so whether the plugin "natively" can handle multiple alarms or not we would still have to ping their servers for each one. Granted we could be "smarter" about it by spacing the time between pings but undoubtedly the end result would still be having to functionally lengthen the `sensorRefresh` time. So all that is to say that we would be right back here! So in summary, I would still recommend you to try changing that config value and see if it helps.

Note that the `sensorRefresh` time only applies to things like contact sensors because SS do not provide open/close events via the API. In other words if your `sensorRefresh` time is 30 seconds and you open a window it could be up to ~30s before you see that reflected in HK. For some people that doesnt matter e.g. if you dont use automations or anything based on these sensors. This would not affect things like alarm events, lock events, etc. You could try setting both homes to 30s or if you dont need sensor events even longer (or make one longer, one shorter, etc.)

Hope that helps!

**Comment by madrobby** [comment]
@shamoon I've set it to `37` and `47` which are both prime numbers so hopefully it doesn't try polling at the same time this way.

It would still be amazing if you could try to reconnect automatically after this error happens, with an increasing timeout.

Right now, I have too manually restart both homebridge instances just because the plugins gets into a state where it essentially gives up on connecting.

**Comment by shamoon** [comment]
Ha, I love the number nerd-age.

Good point, the plugin actually should be lengthening its time between requests and automatically coming back at some point, we implemented that feature a while back (and it works for me still). Sorry I missed that portion of this. Yes, perhaps it would be helpful if you can provide debug logs.
