### ISSUE TITLE
Block Siri Voice Command to Disarm SimpliSafe

### ISSUE THREAD

**Issue by badmaj5** [nzapponi/homebridge-simplisafe3#155]
### Is your feature request related to a problem? Please describe:
Using voice control for Siri allows you to disarm SimpliSafe. This could be a security concern for a bad actor to talk through the glass and disarm the alarm.

### Describe the solution you'd like:
A way to block voice commands from Siri from disarming the system.

### Describe alternatives you've considered:
In researching this I learned the SimpliSafe skill for Alexa has this feature, which is why I’m thinking it could somehow be an option with the SimpliSafe API and not a Siri setting.

### Additional context:
Thanks for listening!

**Comment by shamoon** [comment]
Hi @badmaj5 a few things:

1. This is not possible from our end. The plugin doesn’t “know” where a request comes from so we wouldn’t have any way to act on that.
2. I don’t think there’s as much of a concern here since enabling/disabling security systems with Apple devices including via Siri requires authentication, even on HomePod, see https://www.idownloadblog.com/2018/02/09/homepod-smart-home-security-iphone-authentication/

**Comment by badmaj5** [comment]
Thanks for sharing. I didn’t realize that there was the underlying authentication by Apple. I had tried to disarm the alarm and my phone was already unlocked. But trying to disarm it with the phone locked does trigger me to unlock my phone! I was able to set the alarm without unlocking though, which would go against what was in your article, but isn’t really a concern.

Thanks again for your work on this stuff!
