### ISSUE TITLE
What???

### ISSUE THREAD

**Issue by graanco** [nzapponi/homebridge-simplisafe3#19]
Glassbreak sensor | ❌ | State not provided by SimpliSafe
-- | -- | --
Motion sensor | ❌ | State not provided by SimpliSafe

Hey.... again this is supported it is in the socket.io

also I would set it up so that the socket.io is the verification for the alarm is set.

**Comment by nzapponi** [comment]
Hi,
As stated previously, SimpliSafe doesn't actually provide any state information for the two sensors.
It only provides information if the alarm were to be triggered by a motion or glass break sensor, but the sensor itself isn't reporting any status, and there's no point in showing a sensor that doesn't actually provide information.

**Comment by graanco** [comment]
What do you mean??? The socket.io has all of it... low battery alarming.

**Comment by nzapponi** [comment]
Yes but the socket only triggers when there’s an alarm event, you can’t just query it and it won’t return anything when the system is disarmed. I think it’s misleading to provide a sensor in the Home app if sometimes it doesn’t actually show the correct state.

**Comment by nzapponi** [comment]
It’s the same reason why the SimpliSafe app doesn’t show the state of motion sensors either!

**Comment by graanco** [comment]
I get alerts with motion alarm?? I am not sure in what manner you are saying there... 
even his code has it... 
https://github.com/bachya/simplisafe-python (this was the first one to break the api)

Now my last question is how could we enable message back through the HomeKit to inform you that the a door is open still?

**Comment by nzapponi** [comment]
Sorry, I still don't see much point in adding support for the motion sensor.
When the alarm is off, the motion sensor will **never** provide state information or events, so **even if** someone actually is moving in front of it, the Home app won't reflect it. This is because the REST API won't return any `triggered` flag, and the socket won't provide events when the alarm is off.

When the alarm is armed, the socket will provide an event in case the alarm were to be triggered as a result of the motion sensor picking up a motion. It's the **reason** why the alarm is triggered, it's not really a change in motion sensor state.

Unless you can prove otherwise, I think it's a bad idea to include support for a sensor that will very rarely report information, other than low battery state.

Regarding the following:

> OOPS... Hey you need to add account to the websocket part too... When I arm the other house it messaged me..... That is a major issue there...

Can you please explain what is an issue?

Thanks.

**Comment by graanco** [comment]
You will need to add this to the socket.....

if (data.sid != ss.subId) return;

**Comment by nzapponi** [comment]
Can you please explain what happened exactly?
You received a notification from the wrong property?

**Comment by graanco** [comment]
Can you please explain what happened exactly?
You received a notification from the wrong property? YES... I used the web browser to arm and disarm a house and the one I wasn't configuring alarm changed.

**Comment by graanco** [comment]
Right now I am fix the 480p issue that FFMPEG has with the cameras. I will have an update on that as well.

**Comment by nzapponi** [comment]
Ok, I'll open a separate issue to track the websocket bug.
I'm also not aware of any "480p FFmpeg issues", please expand.
Please open different issues for different topics, there's no point in tracking everything in one place.

The sensor types don't matter, if they do not provide state information. See the screenshot below - even the SimpliSafe app doesn't report on sensor state for motion sensor - there's a good reason for it.
![IMG_0E057DC82294-1](https://user-images.githubusercontent.com/20582065/66399659-efaf6300-e9d7-11e9-8f85-ca956f6df708.jpeg)

**Comment by graanco** [comment]
It comes back to the type of alarm that the user would need to know... Like the glass sensor went I know where and which alarm went off... So when I pull out the tools of choice against the intruder I know where to go.

**Comment by graanco** [comment]
With the camera set to 720p the stream worked. But under 480p settings for the camera(I think this is new which is good for lower bandwidth homes) it doesn't seem to be pulling the video.... Under mine I see this for the stream 848x480 and it is off it should be 640x480.

**Comment by nzapponi** [comment]
> It comes back to the type of alarm that the user would need to know... Like the glass sensor went I know where and which alarm went off... So when I pull out the tools of choice against the intruder I know where to go.

Yes but Apple HomeKit doesn't have the concept of what caused the alarm to trigger. HomeKit only provides the state of sensors and of the alarm system, hence why I would recommend using the official app for any other events. I won't add support for the sensor since I believe it would be misleading, as explained many times before.

**Comment by afalahi** [comment]
@nzapponi the motion sensor can provide "silent notifications" do you think that can be used as an alert to trigger automation?

**Comment by nzapponi** [comment]
See #52
