### ISSUE TITLE
Enhancement: Camera motion detection notifications

### ISSUE THREAD

**Issue by nikonratm** [nzapponi/homebridge-simplisafe3#22]
I'm trying to sort this out, if you can help me understand I can try to do the coding. At the moment we get the CAMERA_MOTION event so seems like should be possible?

I tried adding a motionsensor service to the camera e.g. 
`newAccessory.addService(Service.MotionSensor);`
and then I have the simplicam subscribe to events with a startListening method to simplicam.js with the relevant code:
``` 
case 'CAMERA_MOTION':
     this.accessory.getService(this.Service.MotionSensor).getCharacteristic(Characteristic.MotionDetected).setValue(detected);
```

But like, no dice. Not sure I really understand the logic of why this doesnt work. Thoughts? Totally on the wrong track?

**Comment by nzapponi** [comment]
@nikonratm this is similar to the requests in issue #19 .
I don't recommend implementing this type of support for events such as CAMERA_MOTION because the events are not consistent - you only get these events if the alarm is armed, and you cannot query the camera or the sensor on the state ("is there any motion right now?").

This makes the sensor in the Home app inaccurate and misleading. If you think about it, say you implement the CAMERA_MOTION event so that it shows a motion sensor as "triggered"...

You arm your alarm system, walk in front of the camera, alarm goes off, Home shows the alarm going off and the camera's motion sensor being triggered. How do you then reset that? When does Home know that there is no longer motion happening?

This is why I haven't implemented "stateless" sensors.

In any case, if you do want to try and add support for CAMERA_MOTION in your own fork, you need to re-use the startListening method that you find inside `alarm.js`... That uses `subscribeToEvents` rather than `subscribeToSensor`, which is what gives you that event type.

The events are not tied to a specific sensor, they are alarm events.

**Comment by nikonratm** [comment]
Sorry I should have been more explicit—Im actually talking about a doorbell camera, and those ones do get notifications even when not armed! I updated the title.
`Oct 10 18:54:06 homebridge[13999]: [10/10/2019, 6:54:06 PM] [Home Alarm] Camera received new event from alarm: CAMERA_MOTION`

I already implemented the `startListening` method and thats how Im getting that log above. And as far as setting the state back, I think the doorbell (haven't checked about the indoor cam) seems to have sort of like a "lockout" period where it doesnt push motion alerts for 5 minutes, seems easy enough would be to just settimeout for 5 minutes and then reset the motion sensor, exactly like SS does.

My startListening method has the following but it doesnt work, shouldn't this work as a "service" of the camera accessory?
`this.accessory.getService(this.Service.MotionSensor).getCharacteristic(this.Characteristic.MotionDetected).updateValue(true);`

And for the record, if we do use the timeout, it might be useful to have it push alerts for the indoor camera when the alarm is armed too...

**Comment by nikonratm** [comment]
I got basic support for this working, see my PR above. I think it would be useful to people so perhaps consider merging.

The notifications dont currently [have a screenshot from the camera](https://www.instructables.com/id/Receive-Picture-Notifications-When-People-Approach/) in them, any ideas on why? Perhaps the whole FFMpeg conversion is a limiting factor?

**Comment by nikonratm** [comment]
Turns out the SS socket reports motion events much more frequently than every 5 minutes, it just throttles the notifications. So I changed the 'lockout' to 5seconds which is what [others seem to do](https://github.com/KhaosT/homebridge-camera-ffmpeg/blob/12b17c7f3d0256368e190c0ca8d4e7256fa6cc9d/index.js#L96)

In terms of snapshots, I just still dont get why the `handleSnapshotRequest` method isnt even getting triggered (like nothing in the logs to suggest its getting called at all), thats all we need to get "rich" notifications (which I have from another camera and are really awesome and useful).

**Comment by nzapponi** [comment]
Thanks for the support @nikonratm , really appreciated.
Not having a doorbell camera myself, I wasn't aware that this triggered even while disarmed, it makes sense.

I'll take a look at your PR now!

**Comment by nikonratm** [comment]
Happy to help! Yea I think it’s true for all cameras (regular cameras have a privacy shutter that’s usually closed when alarm is off which disables motion).

I’m really stumped by the snapshot issue, bummer you don’t have a camera to test. I’ll have to take another crack at it some time...

**Comment by nzapponi** [comment]
I think the snapshot issue is due to the fact that HomeKit doesn't have the concept of a "video doorbell"... What you are setting up here is an accessory that provides two services: a camera and a doorbell, but HomeKit doesn't know they're connected in any way, hence it doesn't request a video snapshot if the bell rings.

**Comment by nikonratm** [comment]
Actually I think it kinda does, it’s a camera that has multiple services eg doorbell service, motion service, microphone service etc. 

But also it should do the same for motion alerts. From all of my research online HomeKit is just supposed to show (request) snapshots when motion is triggered in a room with a camera. Making them services on the same accessory should do the same. 

That’s how these do it (and other examples I saw):
https://github.com/rxseger/homebridge-camera-motion
https://github.com/KhaosT/homebridge-camera-ffmpeg/blob/12b17c7f3d0256368e190c0ca8d4e7256fa6cc9d/index.js#L71

**Comment by nzapponi** [comment]
That's weird then... not really sure why! let me know if you do find what the issue is.

**Comment by nikonratm** [comment]
I noticed in another comment you have a camera, any interesting in spending [more of] your valuable time looking into it? If you open the privacy shutter during "home" you can test the motion alerts which should really work the same as doorbell events as far as snapshot requests.

No worries if not, Im still just kinda stumped because I cant find any real documentation and the snapshot request is just supposed to automagically come from HK, except it doesn't 😝

Either way, appreciate all your time on the project.
