### ISSUE TITLE
HW Acceleration Feedback on Raspberry Pi 4

### ISSUE THREAD

**Issue by tasansal** [nzapponi/homebridge-simplisafe3#40]
Wanted to give you feedback about setting up HW acceleration on the Pi 4. May be applicable to Pi 3 as well.

I followed the guide you posted, however it didn't start working until I did these 2 things below. The guide is missing a few libraries that need to be installed that are the full link you included. The performance/delays are pretty much the same, is it normal? It shows 20fps on the stream, I assume that is the frame rate of the video. Can we log the performance of the decoder/encoder as well? The CPU load fell from 140s to 41% though, which is nice.

1) I am running homebridge as a service with systemd. Which required a new "homebridge" user to be created. I had to give the homebridge user access to the GPU using `sudo usermod -a -G video homebridge`
2) Added gpu_mem=192 in /boot/config.txt . The default is 64 apparently, and was crashing to omx decoder.

**Comment by virtualjad** [comment]
@tasansal i'll give these a try to see if there is any improvement on my side. Are you using any add'l ffmpeg args in the homebridge config?

**Comment by tasansal** [comment]
> @tasansal i'll give these a try to see if there is any improvement on my side. Are you using any add'l ffmpeg args in the homebridge config?

Nope, using the parameters @nzapponi suggested. The audio is a little choppy I wonder if we can fix that. Did your work fine without those settings?

**Comment by nikonratm** [comment]
I think some of the initial slowness is due to SS servers which I find just have an absolutely abysmal amount of latency. But FWIW, with default libx264 (software only) I max out at ~9fps (using Pi 3), with omx I'm coming in at 19. And yea, not sure if stream itself is 20fps, the following log makes me think it is?
`Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 20 fps, 20 tbr, 1k tbn, 40 tbc`

Regarding @tasansal 's suggestions for the wiki, I think the first command is only needed for USB attached cameras, I did need to do the second item though. But this kinda stuff is into the weeds of compiling ffmpeg on a Pi, very much a "YMMV" situation...

**Comment by virtualjad** [comment]
Anyone care to share `cameraOptions` parameters that have worked for you? I haven't been able to get HW assist going on an rpi4. libx264 seems to be the only thing that works. I'm not even confident ffmpeg is happy for as much as i've mucked with it.

Also curious if i'm missing any of the hw codecs...

pi@homebridge-pi:~ $ ffmpeg -hwaccels

ffmpeg version N-95554-g9d711a9 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Raspbian 8.3.0-6+rpi1)
  configuration: .... .... ..... ..... .... .... 
  libavutil      56. 35.101 / 56. 22.100
  libavcodec     58. 59.102 / 58. 35.100
  libavformat    58. 33.100 / 58. 20.100
  libavdevice    58.  9.100 / 58.  5.100
  libavfilter     7. 65.100 /  7. 40.101
  libswscale      5.  6.100 /  5.  3.100
  libswresample   3.  6.100 /  3.  3.100
  libpostproc    55.  6.100 / 55.  3.100

Hardware acceleration methods:
vdpau
vaapi
drm

**Comment by nikonratm** [comment]
Codecs aren’t the same thing as “hardware acceleration methods”. I believe your list looks correct, see https://trac.ffmpeg.org/wiki/HWAccelIntro 

I actually tried both building FFmpeg (as in the guide) and installing using apt (they install to different locations so you can set config accordingly). My current config is:
```
                "sourceOptions": {
                    "-vcodec": "h264_mmal"
                },
                "videoOptions": {
                    "-vcodec": "h264_omx",
                    "-tune": false,
                    "-preset": false
                }
```

But if the issue is generally getting HA with FFmpeg working on your Pi, perhaps a thread better suited to another forum? (But let us know if you find anything helpful!)

**Comment by pbr90x** [comment]
At least on Raspberry Pi 4 and Raspbian Buster, there does not appear to be any need to compile your own ffmpeg to get hardware acceleration.  Once I bumped added my homebridge user to the video group (I am running homebridge as a service under systemd), and bumped up gpu_mem to 192 (thanks @tasansal !!!) , transcoding with h264_omx is working like a charm with the native ffmpeg from the raspbian buster apt repo.

**Comment by nikonratm** [comment]
For future reference, this is helpful too: https://retroresolution.com/compiling-ffmpeg-from-source-code-all-in-one-script/ (perhaps we should change README to link to this)
