### ISSUE TITLE
glassbreak and motion sensor support

### ISSUE THREAD

**Issue by afalahi** [nzapponi/homebridge-simplisafe3#52]
First of all, thank you so much for this plugin! it works more consistently than a previous one I tried (that one was solid, but often didn't update the alarm status and camera never work nor automations), AND the cameras actually work!! Some feedback however in your plugin you mentioned the motion sensor has no state, but in SS3 they have silent notifications and can be detected by HomeKit (not sure if this is new or what, but the other plugin had it) thought I'd share that and ask if you plan on supporting it. Thank you, def donating! I was so close to returning SS3 and going with Abode which would've cost me $600 dollars more

**Comment by nikonratm** [comment]
Glad you found this plugin, I agree its more stable. 

Not sure what you mean by "silent" notifications? The glass break and motion sensors only report state while the alarm is armed. Meaning when the system isnt armed they will always show "no motion" which is both inaccurate and not helpful assuming that someone would want to setup automations based on motion. Notifications are provided for the other sensors, contact sensors, etc. Are you saying the other plugin provided motion notifications even when the system was disarmed—are you sure? AFAIK there is no working alternative solution to this, unless something has changed.

**Comment by afalahi** [comment]
Hi @nikonratm thanks for the input! Basically, the motion and entry sensor don’t send notifications when system is off, by default but they send “secret alerts” which i think what the other plugin was leveraging. Am I incorrect in my understanding? I don’t have the other plugin anymore so I can’t test the motion sensor anymore. I hope i didn’t confuse another sensor for the motion... i attached screenshots for contact and motion with the secret alert. Maybe I’m confused about that setting, but when the system is off and door is open and i have secret alerts then my phone gets notified and with the other plugin it logs the entry was opened. Thanks again! 
![79342343-F930-404C-824D-618B81C0538B](https://user-images.githubusercontent.com/26094882/72211791-21d0d500-349f-11ea-941d-c53fee6ac3d0.png)
![8EB6E1C1-6814-45BE-8E6A-A23F3437EEE9](https://user-images.githubusercontent.com/26094882/72211792-22696b80-349f-11ea-8511-7b062acdfdd5.png)

**Comment by nzapponi** [comment]
Interesting, thanks for bringing this up, I think it’s new as I had never seen this before!

I switched secret alerts on for one of my motion sensors, I’ll test them out over the coming days and issue an update to include support if they do work properly!

**Comment by nikonratm** [comment]
Oh wow, I was not aware of that "secret alert" setting. It seems that motion and contact sensors behave differently in that when a contact sensor is set to "disabled" it still sends a push notification via the API which allows us to use it in this plugin (but without getting an alert via SimpliSafe app). Motion sensors on the other hand do not send any notification via API unless its set to a "secret alert" (or alarm). I just tested this and I did in fact get notifications via the API.

My only hesitation is that it might be a bit confusing for people but I guess we can add this as a caveat in the setup instructions? What do you think @nzapponi

**Comment by nikonratm** [comment]
Ps. I can volunteer to implement this

**Comment by afalahi** [comment]
Glad I’m of help! My thinking was since their sensors look nice and to avoid buying another brand and install more apps, i can put one in the bathroom etc and set to secret alerts to turn on lights or trigger the dimmer switch. Thanks again fellas!

**Comment by nzapponi** [comment]
That’s awesome. I think we should implement it and describe in the instructions how to set it up. 

Contact sensors work differently in that they have a state that is always provided. 

The only annoying thing which seems to be happening is that if I turn secret alerts on in the hallway motion sensor, moving in front of it triggers an “event” and therefore my living room camera starts recording, making the privacy shutter open, which is definitely *not* something I want. 

But it’s not for us to decide how people use it: let’s implement it and then leave it to the users to decide how to use it!

@nikonratm up to you! I can do it on Monday, but if you feel like having fun on this on a Sunday, you’re more than welcome to 😉

**Comment by nzapponi** [comment]
See here regarding the behavior I described above with the camera: https://simplisafe.com/forum/customer-support-forum/installing-and-using-simplisafe/secret-alert-triggers-camera

**Comment by afalahi** [comment]
So this applies for all Cameras? Like i have four cans if the sensor sends a secret alert all four record lol? Its not a big deal i guess...

**Comment by graanco** [comment]
Okay if I am right it is the hiddenevent. That does this call. I knew it was on the original and now I know where on the v3. Great... I will make changes :)

**Comment by nikonratm** [comment]
I submitted an initial PR for motion sensor support. I dont have a glass break so not sure about that one.

Should we think about adding a config "toggle" for this? As in, by default motion sensors dont show up since I suspect most people will not be using "silent alarm" setting (the camera privacy shutter thing is pretty annoying) unless you enable the config setting. That way only people who use "silent alerts" can optionally enable support?

**Comment by nikonratm** [comment]
I added more explanation to the readme, I suppose that might be enough information to leave it to users to understand the limitations and decide what they want to do without necessarily implementing the config toggle idea.

**Comment by nzapponi** [comment]
Thanks for this. I’ll review this first thing on Monday! I think I have a pretty cool idea on how to minimize confusion for the end user, I’ll test it out on Monday and report results back here!

**Comment by nzapponi** [comment]
Just released this in v1.4.0. Can anyone please try it?
Please take a look at the readme too! For data consistency, motion sensors will only appear if they are configured with Secret Alert or Alarm in **every** alarm mode. This is to ensure data consistency in the Home app.

Any feedback is appreciated!

If this works well, we can move to other sensor types with similar settings.

**Comment by afalahi** [comment]
@nzapponi sweet! I’ll test today and report back. Explanation in readme is clear and make sense.

**Comment by nikonratm** [comment]
I can confirm this is (still! =) working for me. A couple of notes:
- Now that I had previously setup the accessory in HomeKit, changing the SS settings to "disabled" for Off / Home doesn't actually make the motion sensor disappear in HomeKit. I still see that (helpful!) ['warning'](https://github.com/nzapponi/homebridge-simplisafe3/blob/7af5241ec50ef9cac46f77ae708bf938dbe0f8b1/src/index.js#L305) in the log **Sensor xxx requires secret alerts to be added to Homebridge** but of course its kinda inaccurate in this case. Do we need to explicitly remove the accessory? If I follow plugin logic correctly on the initial run of the plugin after restart it calls `refreshAccessories` with `addAndRemove` set to `true`, do we need to explicitly remove the disabled sensor(s) during that call?
- This little feature also points out another related issue which is that the plugin isnt updated when SS settings change (I noticed this before with camera settings). Im pretty sure theres no socket event to notify the plugin of settings changes so I guess is in order to implement "dynamic" updating of SS settings we'd need to setup another polling method, which perhaps is kinda icky, not to mention whatever other challenges of this. But yea, just mentioning. And if we dont implement, perhaps also worth noting in the readme ("changes take effect after plugin is restarted").

Thoughts?

**Comment by graanco** [comment]
I hate polling and you can with the api use it to change those settings to secret alerts secondly there is tricks that you can do to update setting changes about the camera but why bother. Just pull the stream without settings so those setting come automatically. Also the camera does have a socket.io being pushed which gives you status updates on the camera. Offline online updating etc. 

I wish SS did push out the socket.io with more data.

**Comment by nzapponi** [comment]
I confirm that this is by design.
Regarding the point of sensors not disappearing, this is due to the fact that in the past I have experienced Homebridge suddenly removing and re-adding accessories, meaning that all scenes & automations were lost. As a result, the plugin doesn't automatically clear the existing accessories unless you tell it to do so: just add `"persistAccessories": false` in the config and it'll remove accessories that no longer exist (see Readme)!

Now, regarding SS settings changing, I agree, the only way we can do it today is via polling, and I feel that the situation is bad enough already with the rate limiting / throttling that SS applies to their API endpoints to add any further API calls. I think the compromise for the time being (at least until we better understand the rate limiting) is to ask users to restart Homebridge following a config change.
Far from ideal, I know. Any ideas or feedback about this?

I'll check if there's an event that specifically defines a config update, but I can't recall seeing one in the past!

Hope this makes sense

**Comment by nzapponi** [comment]
My idea behind forcing users to set up secret alerts for every alarm mode on a sensor is my belief (potentially wrong!) that if someone wants to use a motion sensor for something, they want that to work at all times. So it only makes sense that secret alerts are always on.

I personally keep them off due to the camera behavior and the annoying privacy shutter click, but if I did turn it on, I would have it always on!

Would you agree?

**Comment by nikonratm** [comment]
Yea the settings thing doesnt seem worth it, I forgot about the rate-limiting annoyance too. 

But the first issue where the "disabled" motion sensor doesn't automatically disappear after you disable it does feel a bit like unexpected behavior. As in, the plugin is "smart" enough to detect whether the sensor will function properly but only the first time you run the plugin? Here's what I was thinking to change it to:
```
let uuid = UUIDGen.generate(sensor.serial);
let accessory = this.accessories.find(acc => acc.UUID === uuid);

// Check if secret alerts are enabled
if (sensor.setting.off == 0 || sensor.setting.home == 0 || sensor.setting.away == 0) {
     this.log(`Sensor ${sensor.name} requires secret alerts to be added to Homebridge.`);
     if (accessory) { 
          // Sensor won't work properly so we remove it from HomeKit
          this.removeAccessory(accessory);
          this.log(`Removing disabled sensor ${sensor.name}`);
     }
     continue;
}
```

I mostly agree with you that if someone wants a motion sensor they want it to work all of the time but then again I can perhaps imagine a scenario where someone only cares about motion alerts (in HomeKit) when their system is armed. Theres no "right" answer I think, Im sure people will have their own opinions but I guess my thinking is for the plugin to be 100% consistent. Either we show the motion sensor all of the time and let the user decide whether they want a partially-functional sensor in HomeKit or we go all-the-way with the current version where the plugin just doesnt let you have the sensor in HomeKit unless it'll work all of the time.

Thoughts?

**Comment by nzapponi** [comment]
I think we're mixing up two separate issues here:
1. Should the motion sensor work with secret alerts only being enabled *some* of the time?
2. Should the plugin automatically remove accessories from Home once they're removed from SimpliSafe?

Regarding point 1, I think we can go either way, I don't mind. The rationale behind not allowing it to begin with is down to consistency of data in the Home app, but I'm open to changing it if people feel that it would still be useful with partial functionality. @afalahi , what are your thoughts here? What's the use case for you using a SS motion sensor in the Home app?

Regarding point 2, the obvious answer should be *yes*, however I did have some trouble with the plugin clearing out all accessories at times, making it really annoying to set up again. I never managed to troubleshoot it properly but I suspect it might have been due to the API not being reachable due to rate limiting when initializing Homebridge, causing the plugin not to find any accessories and thus clearing existing ones. I'd love to find a better way of managing this, or a way to better troubleshoot the issue so that we solve for it once and for all, and remove the need for `persistAccessories` altogether. I agree, this one is not user friendly at the moment... @nikonratm any ideas? Have you ever had this with any other Homebridge plugins?

**Comment by nikonratm** [comment]
I dont have experience with that particular issue no. I agree its sort of mixing the two issues but I was just addressing this one question which is exactly the overlap between the two issues. But I wanted to tackle the removing just for this specific case, not for the situation where the entire accessory is removed from the SS system. In this situation I think the little snippet [above](https://github.com/nzapponi/homebridge-simplisafe3/issues/52#issuecomment-573923694) would do it. Again, assuming that is the final decision!

**Comment by nzapponi** [comment]
Mmm I'm not too keen on adding a workaround just for one accessory... what you're doing is effectively overriding `persistAccessories` for motion sensors. I'd rather solve the bigger problem if you don't mind!

Could we test keeping `"persistAccessories": false` for a week or so and see if it works fine? If it does, I'm happy to set the default to `false`, which will then make the motion sensor act exactly like you expect it to. What do you think?

**Comment by graanco** [comment]
Really weird how they don’t push notifications for a removal and yet they have it for adding of a sensor device. I guess it because they think that if you buy a sensor your going to use it and not remove it. I’ll have to look into the api more to figure that out.

**Comment by nikonratm** [comment]
@nzapponi Totally see your point there. I will test out `"persistAccessories": false` (creating a backup with third party app right now! 😳)

**Comment by afalahi** [comment]
I didn’t get a chance to install and test the motion sensor again. Will do this weekend but it seems working no?

**Comment by nikonratm** [comment]
Yea so far so good for me.

**Comment by nikonratm** [comment]
@nzapponi I spoke too soon, ran into a nasty bug where I had the "403 forbidden" issue today for the first time in a while and during this restarted HB which erased all of my SS accessories =/

Clearly if we are going to make `persistAccessories` true by default we need to protect against this issue, or it should be reverted back IMHO.

**Comment by nzapponi** [comment]
Shame, that’s what I was dreading. I will revert it back first thing tomorrow, and work on a fix to better manage 403s in general, so we provide a better experience and resolve this issue altogether.

**Comment by nikonratm** [comment]
Yea, it’s a bit of a pain so I agree with reverting the change pending the other changes. WRT better handling of the 403 lockouts, let me know if I can help implement. I have thoughts but not sure what direction you wanted to take
