### ISSUE TITLE
Automations not Firing When SimpliSafe Door Sensor Changes State to Open

### ISSUE THREAD

**Issue by mypupsrgr8** [nzapponi/homebridge-simplisafe3#56]
I am using the current homebridge-simplisafe3 plugin with the latest homebridge package running on MacOS Mojave.  The SimpliSafe devices are being exposed to HomeKit and various HomeKit apps.  I can test the automation in the Home app and the devices to be turned on when the door sensor changes from closed to open turn on as expected.  I have confirmed that the automation is enabled and Imhave restarted homebridge after creating the automation just in case that was the issue.  However, opening the door, and leaving it open until the Home app on iOS and MacOS indicate the door sensor is in an open state, does not result in the automation turning on the expected devices.  Is anyone else experiencing this behavior?  If not, I would appreciate any thoughts on what I might try to troubleshoot.

The automation does have a time restriction to only run between 15 minutes before sunset up until sunrise.  That presumably would not be exercised when testing the automation via the Home app.

Best Regards,

Ted

**Comment by nzapponi** [comment]
Hi Ted, this doesn't seem to be an issue related to the plugin itself... Anyone experiencing the same?

**Comment by mypupsrgr8** [comment]
Hi.  Thanks for the prompt reply.  As a test, I removed the time restriction from the automation and it still did not turn on the two light accessories when the door sensor indicated it was open.  It sometimes takes 5-10 seconds for the sensor to indicate the change in state of the door sensor.  Is this something that can be reduced by a setting in the config file?  I waited for about 45 seconds with the door open and the automation never did turn the accessories on.  Thanks to all for your assistance.

Best Regards,

Ted

**Comment by nikonratm** [comment]
@mypupsrgr8 Yea I have found HK to be pretty flaky when it comes to stuff like this but I dont think its a plugin issue.

The long delay is unfortunately expected because this plugin (and any other unofficial SS one) works by "polling" for the state of the contact sensors every X seconds (default is 15 seconds) since SS dont provide immediate notifications via the API for this. So worst case scenario you open the door just after the last ping and yea, it would be another 15 seconds or so till it updates. You can experiment with setting that frequency lower in the config (`sensorRefresh`) but SS seem to be pretty aggressive about blocking IPs that hit their servers too often so you run the risk. If you do get blocked it seems to usually only be temporary so you can experiment.

But more to your main issue, I have the same one. I have an automation that disables the thermostat when a window opens, this works flawlessly. I have another that turns on a light when a door opens, at night, and this one is super flaky and works a minority of the time. Obviously the sensors and the plugin are exactly the same so I have no real idea why the difference. But I put this on HomeKit more than anything else, unfortunately.

**Comment by nzapponi** [comment]
Just tried it with a SimpliSafe door sensor and a lamp and it worked fine!

Not sure how reliable it is and why it doesn’t work if it doesn’t... it doesn’t seem to be a plug-in issue. 
![439F651B-B92F-48DA-9413-E5007D510093](https://user-images.githubusercontent.com/20582065/73090673-b6d8c280-3ed0-11ea-81c4-6de3ece129a1.png)

**Comment by mypupsrgr8** [comment]
Thanks to all for responding.  I have confirmed that other (possibly all) of my HomeKit automations are no longer working.  I logged my iPad out of iCloud and back in again and still the same issues.  I only have one Apple TV 4K setup as a HomeKit hub and it shows connected.  I have powered it off and back on as well.  It is running tvOS 13.3 (17K449), which it says is the newest version.  My iPad is running iOS 13.3, and my Mac Mini is running macOS Mojave 10.14.1.  That is where Homebridge is running.  So this looks like a more widespread issue than the SimpliSafe plugin or even Homebridge.  I confirmed that even creating a new automation that turns a Lutron Caseta controlled light on that has its own bridge is not working either.  It definitely seems like an issue with the automation functionality.  This is while local on the same WiFi network, not remote access which I’m sure would be worse.

Best Regards,

Ted

**Comment by mypupsrgr8** [comment]
I also do have two-factor authentication enabled on my iPad.  I have also tried to invite my other Apple ID for my work iPhone to my HomeKit Home.  The Home app on that device sees my home configuration, but all accessories show as “No Response”.  I have the invited user set up to be able to change settings, add accessories, etc., but even though the app appears to make changes, when I go back in the changes have not been made.  I also do not see the user listed on the Apple TV.  I do know that the “iCloud Keychain” does not show up as an option under “APPS USING ICLOUD” in iCloud Settings for the work Apple ID on the iPhone.  I suspect this has been done by the iPhone administration in my company.  I don’t know if this could be the issue with the invited user functionality or not.

Best Regards,

Ted

**Comment by nikonratm** [comment]
Ted, as you mentioned, this is likely beyond the scope of this issue. I suggest reaching out in another forum, perhaps the [Homebridge](https://www.reddit.com/r/homebridge/) / [HomeKit](https://www.reddit.com/r/HomeKit/) reddit groups which can be very helpful.

But one thing to try might be to reset your hub (Apple TV).

Please close this when you have the chance.

**Comment by mypupsrgr8** [comment]
@nikonratm thanks for the info.  I have tried power cycling the Apple TV hub with no success.  I will close this issue now.

**Comment by nikonratm** [comment]
Not restarting, **resetting**. Good luck.
