### ISSUE TITLE
SimpliSafe rate limiting causes 403 errors, messing up connectivity and deleting accessories

### ISSUE THREAD

**Issue by nzapponi** [nzapponi/homebridge-simplisafe3#57]
See #52 .

We need to implement a better way of supporting 403 errors.
Ideally, we would like to:
- Monitor for 403 errors
- If they do arise, block requests to SimpliSafe for 5 minutes
- If it still hasn't been resolved after 5 minutes, wait for 10, then 15, and so on

Finally, if a 403 error occurs upon plugin initialization, do **not** refresh or delete accessories from HomeKit.

**Comment by nzapponi** [comment]
@nikonratm here's the approach, what do you think? I can definitely look into implementing this next week.

**Comment by nikonratm** [comment]
Yes this is exactly the approach I had envisioned. 

I also probably wont have time until next week to look at this but sometimes I use this project as an [excellent] distraction from what Im supposed to be working on. If I do find the time / inspiration I'll let you know so we don't duplicate our efforts.

**Comment by nzapponi** [comment]
FYI, I'm working on it, let's not duplicate efforts :)

**Comment by nikonratm** [comment]
Cool, I won’t have a chance for a couple of days anyway. Would love to help, let me know if there’s a part I can take on but I realize it’s not such a big job.

**Comment by nzapponi** [comment]
Should be fixed by #60 once we merge it in.

**Comment by nzapponi** [comment]
Should be fixed with release v1.4.3

**Comment by murphmr** [comment]
Working good for me: 
[2/1/2020, 9:52:06 PM] [Home Alarm] Found 13 cached accessories being configured
[2/1/2020, 9:52:06 PM] Homebridge is running on port 51827.
[2/1/2020, 9:52:06 PM] [Home Alarm] Log in failed due to rate limiting or connectivity, trying again later
[2/1/2020, 9:52:06 PM] [Home Alarm] Refreshing accessories (add and remove: true)
[2/1/2020, 9:52:06 PM] [Home Alarm] Accessory refresh failed due to rate limiting or connectivity
[2/1/2020, 9:53:06 PM] [Home Alarm] Log in attempt failed, still rate limited

Thanks for adding this!
