### ISSUE TITLE
Motion detectors

### ISSUE THREAD

**Issue by krazyflipj** [nzapponi/homebridge-simplisafe3#7]
Any plan to add motion detectors like the below?

https://github.com/graanco/homebridge-SimpliSafePlatform#readme

**Comment by nzapponi** [comment]
@krazyflipj that implementation only displays the sensors in the Home app, but since SimpliSafe 3 doesn't actually provide any status information on those sensors, it's basically useless - it won't show anything even if the sensor triggers.

Here's an example of the data provided by a motion detector:
`
{
            "status": {},
            "setting": {
                "instantTrigger": false,
                "away2": 1,
                "away": 1,
                "home2": 0,
                "home": 0,
                "off": 0
            },
            "name": "Hallway",
            "serial": "XXXXXXXX",
            "type": 4,
            "flags": {
                "swingerShutdown": false,
                "lowBattery": false,
                "offline": false
            }
        }
`

As you can see, the `status` argument is empty!

Does this answer the question?
