### ISSUE TITLE
mkdir error when folder exists

### ISSUE THREAD

**Issue by mbriney** [nzapponi/homebridge-simplisafe3#73]
Getting the following error:

`Feb  3 22:08:45 homebridge homebridge[5266]: [2020-2-3 22:08:45] Error: EEXIST: file already exists, mkdir '/home/pi'
Feb  3 22:08:45 homebridge homebridge[5266]: at Object.fs.mkdirSync (fs.js:885:18)
Feb  3 22:08:45 homebridge homebridge[5266]: at new SimpliSafe3 (/usr/lib/node_modules/homebridge-simplisafe3/simplisafe.js:178:19)
Feb  3 22:08:45 homebridge homebridge[5266]: at new SS3Platform (/usr/lib/node_modules/homebridge-simplisafe3/index.js:65:23)
Feb  3 22:08:45 homebridge homebridge[5266]: at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:337:32)
Feb  3 22:08:45 homebridge homebridge[5266]: at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
Feb  3 22:08:45 homebridge homebridge[5266]: at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
Feb  3 22:08:45 homebridge homebridge[5266]: at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Feb  3 22:08:45 homebridge homebridge[5266]: at Module._compile (module.js:653:30)
Feb  3 22:08:45 homebridge homebridge[5266]: at Object.Module._extensions..js (module.js:664:10)
Feb  3 22:08:45 homebridge homebridge[5266]: at Module.load (module.js:566:32)
Feb  3 22:08:45 homebridge homebridge[5266]: at tryModuleLoad (module.js:506:12)
Feb  3 22:08:45 homebridge homebridge[5266]: at Function.Module._load (module.js:498:3)
Feb  3 22:08:45 homebridge homebridge[5266]: at Function.Module.runMain (module.js:694:10)
Feb  3 22:08:45 homebridge homebridge[5266]: at startup (bootstrap_node.js:204:16)
Feb  3 22:08:45 homebridge homebridge[5266]: at bootstrap_node.js:625:3
Feb  3 22:08:45 homebridge homebridge[5266]: [2020-2-3 22:08:45] Got SIGTERM, shutting down Homebridge..`

**Comment by nikonratm** [comment]
Hmm, try removing the config file e.g. run `rm -rf /home/pi/.simplisafe3.conf` and restart.

What version of node are you running (run `node -v`)? Seems like newer versions [shouldnt throw this error if the path exists and `recursive` is `true`](https://nodejs.org/api/fs.html#fs_fs_mkdir_path_options_callback). But also perhaps we dont even need [that line](https://github.com/nzapponi/homebridge-simplisafe3/blob/6416ca535436127cf0859702613ba09c97846bf5/src/simplisafe.js#L138) since the homedir should always exist @nzapponi ?

**Comment by mbriney** [comment]
That does solve the issue.  Running node v8 due to older hardware.
