### ISSUE TITLE
Vcodec and Config Issues

### ISSUE THREAD

**Issue by mjamison44** [nzapponi/homebridge-simplisafe3#84]
Is there a way to get vcodec | copy to work on the plugin to increase frame rate on the cameras?

Also, the config options on the plugin aren't functioning properly. It gives an error when any FFmpeg flags are added to any of the camera options but they do work just fine when added directly to the plugins code in the simplicam.js file.

**Comment by nikonratm** [comment]
@mjamison44 You may want to visit the Homebridge reddit or HOOBS reddit groups for help troubleshooting specific codec optimization etc as it is highly dependent on your hardware.

How exactly are you adding the options? And what is the error output?

Also, since it sounds like you have cameras working, please close your other open issue: https://github.com/nzapponi/homebridge-simplisafe3/issues/72

**Comment by graanco** [comment]
I am know I am not to knowledgable on things like the cameras but isn't the frame rate based on pktsize for one and the other which is more important is the settings coming from SS. They only give out 20 FPS last I knew.

**Comment by nikonratm** [comment]
@mjamison44 If this issue is resolved please close, otherwise let us know.
