### ISSUE TITLE
Plugin glitches out and polls SimpliSafe API millions of times; IP address blocked by SimpliSafe

### ISSUE THREAD

**Issue by idealdreams** [nzapponi/homebridge-simplisafe3#88]
I've been running this plugin for months now on a Raspberry Pi, mainly with no issues, except for the one I am going to describe.

Every now and again (it seems random), the plugin will glitch out and poll the API hundreds of thousands of times per hour. I know this because I am also running PiHole on the same Raspberry Pi. Every time this issue occurs, the accessories linked to the plugin in the Home App become unresponsive and I can usually resolve the issue by simply restarting Homebridge. When this happens, the CPU on my Raspberry Pi spikes up from 1-2% normally to 50% or so.

This time, however, the glitch happened in the early morning while I was sleeping and I didn't realize until it had polled api.simplisafe.com a total of 5047376 times in the last 24 hours. SimpliSafe appears to have blocked my IP address as now my Raspberry Pi cannot poll the API at all, the accessory is unresponsive, and I can't even log in through the official SimpliSafe app. 

When I disable Wifi on my iPhone and connect through the cell network, I am able to get in just fine. Furthermore, when I turn on my VPN on my MacBook, I can log in from my computer, too. When I try to access it on my network, it simply returns a 403 Forbidden error. 

I called their tech support today and they said they have no way of blocking the IP address and claim the issue is with my ISP. I know this to be false and I'm sure my IP was blocked automatically, presumably as an anti-DDOS measure. I am going to disable Homebridge for a few hours and see if my IP address is automatically unblocked, as it seems the level 1 customer service tech at SimpliSafe has no way to fix this issue on their end.

I am not sure what causes this glitch/issue to happen. I am happy to provide any additional data points I can to help debug this. It seems to occur sporadically and in the 3-4 months I've been using the plugin, it's happened only a handful of times. Today is the first time, however, that my IP address has been blocked by SimpliSafe. I hope it's temporary.

**Comment by nikonratm** [comment]
Hmm, the rate-limiting IP blocking issue is definitely something we have all experienced before (see https://github.com/nzapponi/homebridge-simplisafe3/issues/44 https://github.com/nzapponi/homebridge-simplisafe3/issues/43 https://github.com/nzapponi/homebridge-simplisafe3/issues/12 https://github.com/nzapponi/homebridge-simplisafe3/issues/45 etc). In the past, turning off HB for a while will allow your IP to become un-banned so please let us know if that works.

But also we implemented some attempts to fix this issue see https://github.com/nzapponi/homebridge-simplisafe3/pull/60 which it seems has been generally effective since reports of this issue have basically disappeared. So the question remains what is different about your setup. You mentioned PiHole, do you have any ideas as to why? Are you able to look at PiHole settings / logs etc to see if there are any clues? And are you able to 'whitelist' SS servers / IP addresses in PiHole? Finally, have you tried disabling PiHole to see if that prevents the issue?

Obviously we cant exactly support another piece of software but if theres some way on our end to mitigate / prevent this we'd be happy to.

**Comment by nikonratm** [comment]
Ps. Can you provide Homebridge logs during the excessive calls you were seeing. You should see the plugin trying to prevent this by starting to space-out requests e.g. https://github.com/nzapponi/homebridge-simplisafe3/blob/f4d0111e92733773025f271ec9c3b880ca91eff0/src/simplisafe.js#L208 and if not perhaps PiHole is preventing the plugin from seeing the correct error code (i.e. its not 'recognizing' its getting blocked).

**Comment by murphmr** [comment]
@nikonratm Seeing something similar on MacOSX as well. Attaching a portion my homebridgelog having this issue this morning. Seems like it is getting into some sort of loop with camera disconnects or something like that. 
[
[homebridgelogsnipit.log](https://github.com/nzapponi/homebridge-simplisafe3/files/4470394/homebridgelogsnipit.log)
](url)

**Comment by nikonratm** [comment]
Hey all, I think you guys are right that there's an issue. I've submitted a fix for this that hopefully we can test out.

**Comment by nikonratm** [comment]
@murphmr in response to your email, see https://stackoverflow.com/questions/6743514/how-can-i-fetch-an-unmerged-pull-request-for-a-branch-i-dont-own
